"use strict";

const getAllCookiesMap = async () => {
  const ytMusicCookies = await chrome.cookies.getAll({ domain: "music.youtube.com" });
  const ytCookies = await chrome.cookies.getAll({ domain: ".youtube.com" });
  const map = {};
  for (const c of ytMusicCookies) map[c.name] = c.value;
  for (const c of ytCookies) map[c.name] = c.value;
  return map;
};

const getSpotifyCookiesMap = async () => {
  const spCookies = await chrome.cookies.getAll({ domain: ".spotify.com" });
  const map = {};
  for (const c of spCookies) {
    if (c.name === "sp_dc") {
      map.sp_dc = c.value;
      break;
    }
  }
  return map;
};

let lastSyncTs = 0;
const autoSyncToNutsty = async () => {
  const now = Date.now();
  if (now - lastSyncTs < 3000) return; // Debounce 3s
  lastSyncTs = now;

  try {
    const cookiesMap = await getAllCookiesMap();
    if (!cookiesMap || Object.keys(cookiesMap).length === 0) return;

    const hasSapisid = "SAPISID" in cookiesMap || "__Secure-3PAPISID" in cookiesMap;
    const hasSession = "LOGIN_INFO" in cookiesMap || "SID" in cookiesMap || "__Secure-3PSID" in cookiesMap;

    if (hasSapisid && hasSession) {
      const cookieStr = Object.entries(cookiesMap).map(([k, v]) => `${k}=${v}`).join("; ");
      const res = await fetch("http://127.0.0.1:17890/api/auth/cookies", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ cookies: cookieStr })
      });
      const data = await res.json();
      console.log("[Nutsty Auth Extension] Auto-sync result:", data);
    }
  } catch (err) {
    // Daemon not running or offline
  }
};

// Auto-sync on YouTube Music tab navigation
chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (changeInfo.status === "complete" && tab.url && tab.url.includes("music.youtube.com")) {
    autoSyncToNutsty();
  }
});

// Auto-sync when YouTube cookies change
chrome.cookies.onChanged.addListener((changeInfo) => {
  const domain = changeInfo.cookie.domain || "";
  if (domain.includes("youtube.com") || domain.includes("google.com")) {
    const name = changeInfo.cookie.name;
    if (name === "SAPISID" || name === "__Secure-3PAPISID" || name === "LOGIN_INFO" || name === "SID") {
      autoSyncToNutsty();
    }
  }
});

// Message listener for popup.html actions
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "getYouTubeMusicCookies") {
    (async () => {
      try {
        const cookies = await getAllCookiesMap();
        sendResponse({ success: true, data: { youtubeMusic: cookies } });
      } catch (err) {
        sendResponse({ success: false, error: err.message });
      }
    })();
    return true;
  }

  if (request.action === "getYouTubeMusicCookiesNetscape") {
    (async () => {
      try {
        const ytMusic = await chrome.cookies.getAll({ domain: "music.youtube.com" });
        const yt = await chrome.cookies.getAll({ domain: ".youtube.com" });
        const all = [...ytMusic, ...yt];
        let out = "# Netscape HTTP Cookie File\n# Generated by Nutsty / SimpMusic Helper\n\n";
        for (const c of all) {
          out += `${c.domain}\t${c.domain.startsWith(".") ? "TRUE" : "FALSE"}\t${c.path || "/"}\t${c.secure ? "TRUE" : "FALSE"}\t${c.expirationDate ? Math.round(c.expirationDate) : "0"}\t${c.name}\t${c.value}\n`;
        }
        sendResponse({ success: true, data: { netscapeFormat: out } });
      } catch (err) {
        sendResponse({ success: false, error: err.message });
      }
    })();
    return true;
  }

  if (request.action === "getSpotifyCookies") {
    (async () => {
      try {
        const sp = await getSpotifyCookiesMap();
        sendResponse({ success: true, data: { spotify: sp } });
      } catch (err) {
        sendResponse({ success: false, error: err.message });
      }
    })();
    return true;
  }
});